export const INCREMENT = 'INCREMENT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const USER_LOADING = 'USER_LOADING';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';

export const ADD_SURVEY = 'ADD_SURVEY';
export const CLEAR_SURVEY = 'CLEAR_SURVEY';
export const GET_UNAPPROVED_SURVEY = 'GET_UNAPPROVED_SURVEY';
export const GET_APPROVED_SURVEY = 'GET_APPROVED_SURVEY';
export const GET_PUBLISHED_SURVEY = 'GET_PUBLISHED_SURVEY';

export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_SUB_USERS = 'SET_SUB_USERS';
export const ADD_SUB_USER = 'ADD_SUB_USER';

export const ADD_ALBUM = 'ADD_ALBUM';